services:
  app:
    build:
      context: ./app
    container_name: app
    user: "1000:1000"
    volumes:
      - ./app/src:/var/www/html/src
      - ./app/vendor:/var/www/html/vendor
      - ./nginx/myconfig.ini:/usr/local/etc/php/conf.d/myconfig.ini
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./app/src:/var/www/html/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app99
    ports:
      - "3000:3306" # On the php side we use db:3306 to connect cause we are inside
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
    driver: bridge
