services:
  app:
    build:
      context: ./app
    container_name: app
    volumes:
      - ./app:/var/www/html   # Monta la tua applicazione PHP
      - ./nginx/myconfig.ini:/usr/local/etc/php/conf.d/myconfig.ini
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # Monta la configurazione personalizzata di Nginx
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge